# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c5a8727399f470cc501386a116077fe12c31527b1b6ec3c6f7ce02cbd4e7973d6be3d318bdaacd639477817b3b9265c32e8e6fc8ac101a48fc9a2e8fa0c78cc

test:
  secret_key_base: c01a737d89685979cbb692e443d7775a0c1fe6878d3f0347339897fdc9a000c354a51ac0c1d517163359b23cf50252c687b196f8aa77f47c2db8c8aaafd14337

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
